--- 
apiVersion: apps/v1
kind: Deployment
metadata: 
  labels: 
    app: loginapp
  name: loginapp
spec: 
  replicas: 2
  selector: 
    matchLabels: 
      app: loginapp
  template: 
    metadata: 
      labels: 
        app: loginapp
    spec: 
      containers: 
        - 
          image: "shraddhagaikwad52/demo:latest"
          imagePullPolicy: Always
          name: loginapp
